name: Continuous Delivery Pipeline
'on':
  push:
    branches:
      - master
jobs:
  deployingProd:
    name: Deployment to Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OpenShift Actions
        uses: redhat-actions/oc-installer@v1
        with:
          version: 3.11.230
      - name: Executing OC Commands
        run: >
          echo ${{ secrets.OC_SERVER_URL }} | sed 's/./& /g'
          
          oc login ${{ secrets.OC_SERVER_URL }} --token=${{ secrets.OC_API_TOKEN
          }}

          oc start-build ${{ github.event.repository.name }} --follow || oc
          new-app https://www.github.com/${{ github.repository }} --name=${{
          github.event.repository.name }}
